  -- 06-contratos (2/2): acuerdos de crédito en PDF.
  --
  -- - Tabla `contratos`: comprobante derivado de una factura (venta a crédito)
  --   o de una compra (compra a crédito). El PDF es inmutable; si el origen
  --   cambia, el contrato se anula y se genera otro.
  -- - Un solo contrato activo (generado/enviado/firmado) por origen: índices
  --   únicos parciales. El servicio comprueba antes para dar el mensaje claro.
  -- - Trigger `contratos_validar`: origen a crédito y no anulado al insertar,
  --   deriva `fecha_vencimiento = fecha del origen + dias_credito`, solo deja
  --   cambiar `estado`/`notas` y valida las transiciones de estado.
  -- - Vista `contratos_listado_view` (security_invoker) para listar/buscar.
  -- - RLS solo admin, sin `delete` (los contratos se anulan, no se borran).
  -- - Bucket privado `contratos` (5 MB, solo PDF), sin política de `update`.
  -- - `numero` es identity `by default` + RPC `siguiente_numero_contrato()`: el
  --   servicio reserva el número antes de renderizar el PDF (el PDF lo lleva
  --   impreso y se sube antes de insertar la fila). Un fallo deja un hueco en la
  --   numeración, nunca un duplicado (unique).

  -- ============ TABLA ============
  create table public.contratos (
    id uuid primary key default gen_random_uuid(),
    numero bigint generated by default as identity unique,
    tipo text not null check (tipo in ('venta_credito', 'compra_credito')),
    factura_id uuid references public.facturas(id),
    compra_id uuid references public.compras(id),
    fecha date not null,
    dias_credito int not null check (dias_credito between 0 and 365),
    fecha_vencimiento date not null,
    estado text not null default 'generado'
      check (estado in ('generado', 'enviado', 'firmado', 'anulado')),
    url_storage text not null,
    notas text check (notas is null or char_length(notas) <= 500),
    generado_por uuid not null default auth.uid() references auth.users(id),
    estado_cambiado_por uuid references auth.users(id),
    estado_cambiado_at timestamptz,
    created_at timestamptz not null default now(),
    constraint contratos_origen_check check (
      (tipo = 'venta_credito' and factura_id is not null and compra_id is null)
      or (tipo = 'compra_credito' and compra_id is not null and factura_id is null)
    )
  );

  create unique index contratos_factura_activo_uq
    on public.contratos (factura_id)
    where factura_id is not null and estado <> 'anulado';

  create unique index contratos_compra_activo_uq
    on public.contratos (compra_id)
    where compra_id is not null and estado <> 'anulado';

  create index idx_contratos_fecha on public.contratos (fecha desc, numero desc);
  create index idx_contratos_estado on public.contratos (estado);

  -- ============ NÚMERO ============
  -- Reserva el siguiente número de contrato (solo admin). `security invoker`:
  -- usa el privilegio de secuencia del rol `authenticated`.
  create or replace function public.siguiente_numero_contrato()
  returns bigint
  language plpgsql
  security invoker
  set search_path = public
  as $$
  begin
    if not public.es_admin() then
      raise exception 'Solo un administrador puede generar contratos'
        using errcode = '42501';
    end if;
    return nextval(pg_get_serial_sequence('public.contratos', 'numero'));
  end;
  $$;

  revoke all on function public.siguiente_numero_contrato() from public;
  grant execute on function public.siguiente_numero_contrato() to authenticated;
  grant usage on sequence public.contratos_numero_seq to authenticated;

  -- ============ TRIGGER DE VALIDACIÓN ============
  create or replace function public.contratos_validar()
  returns trigger
  language plpgsql
  security invoker
  set search_path = public
  as $$
  declare
    v_condicion text;
    v_estado text;
    v_fecha date;
  begin
    if tg_op = 'INSERT' then
      if new.tipo = 'venta_credito' then
        select f.condicion, f.estado, f.fecha
          into v_condicion, v_estado, v_fecha
        from public.facturas f
        where f.id = new.factura_id;
      else
        select c.condicion, c.estado, c.fecha
          into v_condicion, v_estado, v_fecha
        from public.compras c
        where c.id = new.compra_id;
      end if;

      if v_fecha is null then
        raise exception 'El documento de origen del contrato no existe'
          using errcode = '23514';
      end if;
      if v_condicion <> 'credito' then
        raise exception 'Solo se generan contratos de documentos a crédito'
          using errcode = '23514';
      end if;
      if v_estado = 'anulada' then
        raise exception 'El documento de origen está anulado'
          using errcode = '23514';
      end if;

      -- Derivados: el valor enviado se ignora.
      new.fecha_vencimiento := v_fecha + new.dias_credito;
      new.estado := 'generado';
      new.estado_cambiado_por := null;
      new.estado_cambiado_at := null;
      return new;
    end if;

    -- UPDATE: solo `estado` y `notas` son editables.
    if new.id <> old.id
      or new.numero <> old.numero
      or new.tipo <> old.tipo
      or new.factura_id is distinct from old.factura_id
      or new.compra_id is distinct from old.compra_id
      or new.fecha <> old.fecha
      or new.dias_credito <> old.dias_credito
      or new.fecha_vencimiento <> old.fecha_vencimiento
      or new.url_storage <> old.url_storage
      or new.generado_por <> old.generado_por
      or new.created_at <> old.created_at then
      raise exception 'Un contrato generado no se modifica: solo cambian su estado y sus notas'
        using errcode = '23514';
    end if;

    if new.estado <> old.estado then
      if not (
        (old.estado = 'generado' and new.estado in ('enviado', 'firmado', 'anulado'))
        or (old.estado = 'enviado' and new.estado in ('firmado', 'anulado'))
        or (old.estado = 'firmado' and new.estado = 'anulado')
      ) then
        raise exception 'Cambio de estado no permitido: de % a %', old.estado, new.estado
          using errcode = '23514';
      end if;
      new.estado_cambiado_por := auth.uid();
      new.estado_cambiado_at := now();
    else
      new.estado_cambiado_por := old.estado_cambiado_por;
      new.estado_cambiado_at := old.estado_cambiado_at;
    end if;

    return new;
  end;
  $$;

  create trigger contratos_validar
    before insert or update on public.contratos
    for each row execute function public.contratos_validar();

  -- ============ VISTA DE LISTADO ============
  -- `busqueda`: texto normalizado (número de contrato, número de factura,
  -- nombre y RIF/CI de la contraparte) para filtrar `?q=` con un solo `ilike`.
  create or replace view public.contratos_listado_view
  with (security_invoker = true) as
  select
    ct.id,
    ct.numero,
    ct.tipo,
    ct.factura_id,
    ct.compra_id,
    ct.fecha,
    ct.dias_credito,
    ct.fecha_vencimiento,
    ct.estado,
    ct.url_storage,
    ct.notas,
    ct.generado_por,
    ct.estado_cambiado_por,
    ct.estado_cambiado_at,
    ct.created_at,
    coalesce(f.cliente_id, c.proveedor_id) as contraparte_id,
    coalesce(cl.nombre, pr.nombre) as contraparte_nombre,
    coalesce(cl.rif_ci, pr.rif_ci) as contraparte_rif_ci,
    coalesce(f.fecha, c.fecha) as documento_fecha,
    f.numero as documento_numero,
    coalesce(f.total_usd, c.subtotal_usd) as monto_usd,
    (coalesce(f.estado, c.estado) = 'anulada') as origen_anulado,
    lower(
      ct.numero::text || ' ' || lpad(ct.numero::text, 4, '0') || ' '
      || coalesce(f.numero::text || ' ' || lpad(f.numero::text, 6, '0'), '') || ' '
      || coalesce(cl.nombre, pr.nombre, '') || ' '
      || coalesce(cl.rif_ci, pr.rif_ci, '')
    ) as busqueda
  from public.contratos ct
  left join public.facturas f on f.id = ct.factura_id
  left join public.clientes cl on cl.id = f.cliente_id
  left join public.compras c on c.id = ct.compra_id
  left join public.proveedores pr on pr.id = c.proveedor_id;

  -- ============ RLS ============
  alter table public.contratos enable row level security;

  create policy "contratos_select_admin" on public.contratos
    for select to authenticated using (public.es_admin());
  create policy "contratos_insert_admin" on public.contratos
    for insert to authenticated with check (public.es_admin());
  create policy "contratos_update_admin" on public.contratos
    for update to authenticated
    using (public.es_admin())
    with check (public.es_admin());
  -- Sin política de delete: los contratos se anulan, no se borran.

  -- ============ BUCKET DE STORAGE ============
  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values ('contratos', 'contratos', false, 5242880, array['application/pdf'])
  on conflict (id) do nothing;

  -- Solo admin. Sin `update`: el PDF es inmutable (se sube con upsert: false).
  -- `delete` solo para limpiar el archivo si falla el insert de la fila.
  create policy "contratos_storage_select"
    on storage.objects for select to authenticated
    using (bucket_id = 'contratos' and public.es_admin());
  create policy "contratos_storage_insert"
    on storage.objects for insert to authenticated
    with check (bucket_id = 'contratos' and public.es_admin());
  create policy "contratos_storage_delete"
    on storage.objects for delete to authenticated
    using (bucket_id = 'contratos' and public.es_admin());
